<?php
$this->layout('layout/portal');
$this->layout( )->setVariable('view', 'error');
?>
<div class="layout__section row">
<?php
    $title = "Internal Server Error";
    $errorCode = 500;
    $errorMsg = "We're sorry, but an internal server error has occurred.";
    if (isset($this->exception) && $this->exception->getCode() > 200) {
        $errorCode = $this->exception->getCode();
        if ($errorCode == 401 || $errorCode == 403) {
            $title = "Unauthorized";
            $errorMsg = "";
        }
    }
?>
    <h1>Error <?="$errorCode: $title"?></h1>
    <div class="layout__content--display">
        <p><?=$errorMsg?></p>
<?php if (isset($this->exception) && $this->exception instanceof \Exception\User) { ?>
        <h4><?=$this->escapeHtml($this->exception->getMessage( ))?></h4>
<?php } ?>
        <p>
            For more information, please

                contact us via email
            </a>
            <br>or reach us directly at <a href="tel:+18557497322">+1&nbsp;(855)&nbsp;749-7322 (toll-free)</a>.
        </p>
    </div>
</div>
<?php if (isset($this->display_exceptions) && $this->display_exceptions) { ?>
<div class="layout__section row">
<?php   if (isset($this->exception) && $this->exception instanceof \Throwable) { ?>
    <h2>Additional information</h2>
    <div class="layout__content--display">
<h4><?=$this->escapeHtml(get_class($this->exception))?></h4>
<dl>
    <dt>File</dt>
    <dd>
        <pre class="prettyprint linenums"><?=$this->escapeHtml($this->exception->getFile( ))?>:<?=$this->escapeHtml($this->exception->getLine( ))?></pre>
    </dd>
    <dt>Message</dt>
    <dd>
        <pre class="prettyprint linenums"><?=$this->escapeHtml($this->exception->getMessage( ))?></pre>
    </dd>
    <dt>Stack trace</dt>
    <dd>
        <pre class="prettyprint linenums"><?=$this->escapeHtml($this->exception->getTraceAsString( ))?></pre>
    </dd>
</dl>
<?php       if ($e = $this->exception->getPrevious( )) { ?>
<?php           $icount = 0; ?>
    <h3>Previous exceptions</h3>
<ul class="unstyled">
<?php           do { ?>
    <li>
        <h3><?=$this->escapeHtml(get_class($e))?></h3>
        <dl>
            <dt>File</dt>
            <dd>
                <pre class="prettyprint linenums"><?=$this->escapeHtml($e->getFile( ))?>:<?=$this->escapeHtml($e->getLine( ))?></pre>
            </dd>
            <dt>Message</dt>
            <dd>
                <pre class="prettyprint linenums"><?=$this->escapeHtml($e->getMessage( ))?></pre>
            </dd>
            <dt>Stack trace</dt>
            <dd>
                <pre class="prettyprint linenums"><?=$this->escapeHtml($e->getTraceAsString( ))?></pre>
            </dd>
        </dl>
    </li>
<?php               if (++$icount >= 50) { ?>
    <li>There may be more exceptions but we don't have enough memory to process them.</li>
<?php                   break; ?>
<?php               } ?>
<?php           } while ($e = $e->getPrevious( )); ?>
</ul>
<?php       } ?>
</div>
<?php   } else { ?>
<h4>No Exception available</h4>
<?php   } ?>
</div>
<?php } ?>
